language: r
dist: trusty
sudo: required
cache: packages
services:
- docker
warnings_are_errors: false
r:
- devel
r_packages:
- devtools
- roxygen2
before_install:
- cd omlTuneBenchRLocal
before_script:
- R --no-save <<< 'library("devtools"); document()'
